
# docker-compose.yml
#version: '3.8'

services:
  backend:
    build: ./server
    ports:
      - "5100:5100"
    depends_on:
      - db
    environment:
      - PORT=5100
      - DATABASE_URL=postgres://user:password@db:5432/mydb # Replace with your DB details
      # ... other environment variables

  frontend:
    build: ./client
    ports:
      - "19000:19000" # Expo default port
    depends_on:
      - backend
    volumes:
      - ./client:/app # Mount the frontend code

  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydb
    volumes:
      - db_data:/var/lib/postgresql/data # Persist database data

volumes:
  db_data: